blank_issues_enabled: false
contact_links:
  - name: OSlash Security
    url: https://www.oslash.com/security
    about: Contact the Security team at OSlash if you think you've found a security issue.
